# Generated by Django 4.1.2 on 2023-01-04 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirpapp', '0002_alter_post_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
