# Generated by Django 4.1.2 on 2023-01-06 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirpapp', '0003_rename_author_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
