# Generated by Django 4.1.4 on 2022-12-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_description', models.CharField(max_length=300)),
                ('date_created', models.DateField(verbose_name='date created')),
                ('date_completed', models.DateField(verbose_name='date completed')),
                ('is_complete', models.BooleanField(verbose_name='is complete')),
            ],
        ),
    ]
