# Generated by Django 4.1.3 on 2023-01-02 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0002_alter_post_image"),
    ]

    operations = [
        migrations.AlterModelOptions(name="post", options={"ordering": ("-id",)},),
        migrations.AlterField(
            model_name="post",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
