from django import forms
from .models import Shortened
from .utils import code_generator


# form to show user to shorten the url
class UrlShortenerForm(forms.ModelForm):
    # url field to display to user to enter the url to shorten
    # the class form-control form-control-lg is just for bootstrap styling
    url = forms.URLField(widget=forms.URLInput(
        attrs={"class": "form-control form-control-lg", "placeholder": "Enter url"}))
    
    # when saving the shortner form add the code to it
    def save(self, commit=True):
        instance = super().save(commit=False)
        
        #add the code generated by the code_generator to the instance 
        instance.code = code_generator()
        if commit:
            # if commit is true we save the instance with the code and long url
            instance.save()
        return instance

    class Meta:
        model = Shortened

        fields = ('url',)