# Generated by Django 4.1.4 on 2022-12-28 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_short', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BothUrls',
            new_name='BothUrl',
        ),
    ]
