# Generated by Django 4.1.4 on 2022-12-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
