# Generated by Django 4.1.4 on 2022-12-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortened",
            name="code",
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
