# Generated by Django 4.1.4 on 2022-12-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date published'),
        ),
    ]
