# Generated by Django 4.1.4 on 2022-12-28 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0003_remove_urls_short_url_urls_short_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Urls',
            new_name='Url',
        ),
    ]
