# Generated by Django 4.1.4 on 2022-12-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0004_rename_urls_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='times_clicked',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
