# Generated by Django 4.1.4 on 2022-12-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0005_url_times_clicked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
