# Generated by Django 4.1.4 on 2022-12-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0006_alter_url_short_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='times_clicked',
            field=models.IntegerField(default=0),
        ),
    ]
