# Generated by Django 4.1.4 on 2022-12-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='short_code',
            field=models.CharField(max_length=20),
        ),
    ]
