# Generated by Django 4.1.4 on 2023-01-14 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalized_index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalizedIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_allocation', models.IntegerField()),
                ('market_cap_min', models.IntegerField()),
                ('dividend_yield_min', models.FloatField()),
                ('pe_ratio_max', models.FloatField()),
                ('sector_exclude_1', models.CharField(max_length=200)),
                ('sector_exclude_2', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
