# Generated by Django 4.1.5 on 2023-01-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalized_index', '0002_personalizedindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizedindex',
            name='index_name',
            field=models.CharField(default='my_index', max_length=200),
        ),
    ]
