# Generated by Django 4.1.5 on 2023-01-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalized_index', '0003_personalizedindex_index_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sector', models.CharField(max_length=200)),
                ('longBusinessSummary', models.CharField(max_length=2500)),
                ('country', models.CharField(max_length=200)),
                ('shortName', models.CharField(max_length=200)),
                ('trailingEps', models.FloatField()),
                ('forwardPE', models.FloatField()),
                ('marketCap', models.FloatField()),
                ('dividendYield', models.FloatField()),
                ('trailingPE', models.FloatField()),
            ],
        ),
    ]
