# Generated by Django 4.1.5 on 2023-01-24 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalized_index', '0004_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='dividendYield',
            new_name='dividend_yield',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='forwardPE',
            new_name='forward_pe',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='longBusinessSummary',
            new_name='long_business_summary',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='marketCap',
            new_name='market_cap',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='shortName',
            new_name='short_name',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='trailingEps',
            new_name='trailing_eps',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='trailingPE',
            new_name='trailing_pe',
        ),
    ]
