# Generated by Django 4.1.5 on 2023-01-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalized_index', '0005_rename_dividendyield_stock_dividend_yield_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='dividend_yield',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='forward_pe',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='long_business_summary',
            field=models.CharField(max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='market_cap',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sector',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='short_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='trailing_eps',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='trailing_pe',
            field=models.FloatField(null=True),
        ),
    ]
