# Generated by Django 4.1.5 on 2023-01-27 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalized_index', '0007_personalizedindexstock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalizedindexstock',
            old_name='personalized_index_id',
            new_name='personalized_index',
        ),
    ]
