# Generated by Django 4.1.4 on 2022-12-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(default='9Yy7HY82rpCr', max_length=12),
        ),
    ]
