# Generated by Django 4.1.4 on 2022-12-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_manager', '0002_alter_url_short_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='short_url',
        ),
        migrations.AddField(
            model_name='url',
            name='code',
            field=models.CharField(default='Bqk8104CtiCK', max_length=12),
        ),
    ]
