# Generated by Django 4.1.4 on 2022-12-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_manager', '0003_remove_url_short_url_url_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='code',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
